version: '2.29.1'
services:
  database:
    restart: on-failure
    container_name: postgresql
    image: 
      postgres: alpine
    ports:
      - "5432:5432"

  taskmanager:
    restart: on-failure
    container_name: taskmanager
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    