FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /taskmanager
COPY pom.xml .
COPY src ./src
RUN mvn clean package -Dmaven.test.skip


FROM openjdk:17-slim
WORKDIR /taskmanager
COPY --from=build /taskmanager/target/*.jar taskmanager.jar
EXPOSE 8080
ENTRYPOINT [ "java", "-jar", "./taskmanager.jar"]